[2023-09-10 19:27:21] [    INFO] 10001329: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10453929: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10015627: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10019573: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10269741: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10063764: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10064275: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10042538: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20024696: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20147086: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20247372: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20022619: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20077523: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10115297: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20027883: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20246629: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 10022718: * Storing teachers...
[2023-09-10 19:27:21] [    INFO] 20148306: * Storing teachers...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/qrtrenh/programming/VPlan_fr/backend/load_plans.py", line 142, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/qrtrenh/programming/VPlan_fr/backend/load_plans.py", line 128, in main
    await asyncio.gather(
  File "/home/qrtrenh/programming/VPlan_fr/backend/load_plans.py", line 30, in check_infinite
    downloaded_files = await self.plan_downloader.update_fetch()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qrtrenh/programming/VPlan_fr/backend/plan_downloader.py", line 70, in update_fetch
    new |= await self.fetch_indiware_mobil(indiware_client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qrtrenh/programming/VPlan_fr/backend/plan_downloader.py", line 86, in fetch_indiware_mobil
    plan_files = await indiware_client.fetch_dates()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qrtrenh/programming/VPlan_fr/venv/lib/python3.11/site-packages/stundenplan24_py/client.py", line 291, in fetch_dates
    filename, date_str = _out[i:i + 2]
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
